apiVersion: v1
kind: Pod
metadata:
  name: flask-app
  namespace: flask-app
spec:
  containers:
    - name: flask-app
      image: trivedirohit/mini-flask-app:latest
      ports:
        - containerPort: 80
